version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=mypassword
  hex:
    image: hex:latest
    ports:
      - "3000:3000"
    depends_on:
      - db