version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '6379:6379'
    expose:
      # Opens port 3306 on the container
      - '6379'
    volumes:
      - redis-data:/data
  media:
    image: media:latest
    environment:
      MYSQL_CONNECTION: 'root:password@tcp(db:3306)/db?charset=utf8&parseTime=True&loc=Local'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - auth
  auth:
    image: auth:latest
    ports:
      - "8081:8081"
    depends_on:
      - redis
# Names our volume
volumes:
  my-db:
  redis-data: